[package]
name = "keepcalm"
version = "0.1.0"
edition = "2021"
description = "Simple shared types for multi-threaded programs"

[dependencies]
serde = { version = "1", optional = true }

[features]
serde = ["dep:serde"]

[lib]
name = "keepcalm"
