[package]
name = "keepcalm"
version = "0.1.3"
edition = "2021"
description = "Simple shared types for multi-threaded programs"
license = "Apache-2.0 OR MIT"
readme = "README.md"
repository = "https://github.com/mmastrac/keepcalm"

[dependencies]
serde = { version = "1", optional = true }

[features]
serde = ["dep:serde"]
