[package]
name = "keepcalm"
version = "0.2.5"
edition = "2021"
description = "Simple shared types for multi-threaded programs"
license = "Apache-2.0 OR MIT"
readme = "README.md"
repository = "https://github.com/mmastrac/keepcalm"

[dependencies]
serde = { version = "1", optional = true }
parking_lot = { version = "0.12.1", features = ["send_guard"] }
once_cell = "1"

[dev_dependencies]
paste = "1"

[features]
serde = ["dep:serde"]
global_experimental = []
