name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build (default)
      run: cargo build --verbose
    - name: Run tests (all features)
      run: cargo test --all-features --verbose
    - name: Run docs
      run: cargo doc --all-features --verbose
