name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install nightly toolchain
      run: rustup toolchain add nightly
    - name: Build (default)
      run: cargo build --verbose
    - name: Cargo clippy
      run: cargo clippy
    - name: Cargo clippy (all features)
      run: cargo clippy --all-features
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests (all features)
      run: cargo test --all-features --verbose
    - name: Run docs
      run: cargo doc --all-features --verbose
    - name: Run Miri
      run: rustup component add miri && MIRIFLAGS=-Zmiri-disable-isolation cargo +nightly miri test --all-features
